### ISSUE TITLE
pip install batterydataextractor failed

### ISSUE THREAD

**Issue by gaoxinzhong1992** [ShuHuang/batterydataextractor#4]
> Hi, I use pip install batterydataextractor on a mac m1 computer. I am using python version 3.9.13, and it prompts that the installation failed.

```
The error message is as follows:
 Running setup.py install for nmslib ... error
  error: subprocess-exited-with-error

  × Running setup.py install for nmslib did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Dependence list: ['pybind11<2.6.2', 'psutil', "numpy>=1.10.0,<1.17 ; python_version=='2.7'", "numpy>=1.10.0 ; python_version>='3.5'"]
      /Users/rzht/Documents/workspace/batterydataextractor_v1/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```

> 

 

>

**Comment by gaoxinzhong1992** [comment]
example 

> from batterydataextractor.doc.text import Paragraph
> text = '1H NMR spectra were recorded on a Varian MR-400 MHz instrument.'
> doc = Paragraph(text)
> doc.add_general_models(["apparatus"], confidence_threshold=0.1, original_text=True)
> for record in doc.records:
>     print(record.serialize())

error:

> /home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
>   return torch._C._cuda_getDeviceCount() > 0
> /home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/torch/__init__.py:696: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
>   _C._set_default_tensor_type(t)
> Traceback (most recent call last):
>   File "/home/gaoxzh/workspace/main.py", line 5, in <module>
>     for record in doc.records:
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/batterydataextractor/doc/text.py", line 334, in records
>     return ModelList(*[r for sent in self.sentences for r in sent.records])
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/batterydataextractor/utils.py", line 26, in fget_memoized
>     setattr(self, attr_name, fget(self))
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/batterydataextractor/doc/text.py", line 228, in sentences
>     spans = self.sentence_tokenizer.span_tokenize(self.text)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/batterydataextractor/nlp/tokenize.py", line 81, in span_tokenize
>     self._tokenizer = spacy.load(self.model)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/__init__.py", line 50, in load
>     return util.load_model(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/util.py", line 324, in load_model
>     return load_model_from_package(name, **kwargs)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/util.py", line 357, in load_model_from_package
>     return cls.load(vocab=vocab, disable=disable, exclude=exclude, config=config)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/en_core_sci_sm/__init__.py", line 10, in load
>     return load_model_from_init_py(__file__, **overrides)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/util.py", line 517, in load_model_from_init_py
>     return load_model_from_path(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/util.py", line 392, in load_model_from_path
>     nlp = load_model_from_config(config, vocab=vocab, disable=disable, exclude=exclude)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/util.py", line 429, in load_model_from_config
>     nlp = lang_cls.from_config(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/language.py", line 1672, in from_config
>     nlp.add_pipe(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/language.py", line 774, in add_pipe
>     pipe_component = self.create_pipe(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/spacy/language.py", line 660, in create_pipe
>     resolved = registry.resolve(cfg, validate=validate)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/thinc/config.py", line 746, in resolve
>     resolved, _ = cls._make(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/thinc/config.py", line 795, in _make
>     filled, _, resolved = cls._fill(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/thinc/config.py", line 850, in _fill
>     filled[key], validation[v_key], final[key] = cls._fill(
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/thinc/config.py", line 849, in _fill
>     promise_schema = cls.make_promise_schema(value, resolve=resolve)
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/site-packages/thinc/config.py", line 1057, in make_promise_schema
>     return create_model("ArgModel", **sig_args)
>   File "pydantic/main.py", line 990, in pydantic.main.create_model
>   File "pydantic/main.py", line 299, in pydantic.main.ModelMetaclass.__new__
>   File "pydantic/fields.py", line 411, in pydantic.fields.ModelField.infer
>   File "pydantic/fields.py", line 342, in pydantic.fields.ModelField.__init__
>   File "pydantic/fields.py", line 451, in pydantic.fields.ModelField.prepare
>   File "pydantic/fields.py", line 550, in pydantic.fields.ModelField._type_analysis
>   File "/home/gaoxzh/anaconda3/envs/py39/lib/python3.9/typing.py", line 852, in __subclasscheck__
>     return issubclass(cls, self.__origin__)
> TypeError: issubclass() arg 1 must be a class
